[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FourierFlows = "2aec4490-903f-5c70-9b11-9bed06a700e1"
GeophysicalFlows = "44ee3b1c-bc02-53fa-8355-8e347616e15e"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QGDipoles = "192f05a4-068c-458e-9e9e-a50cd96b7215"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
